/*
 *Esta interface se utiliza para registrar un nuevo usuario en el sistema de 
 *facturacion 
 */
package administracion;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;




/**
 *
 * @author Pedro Ernesto ALfaro Lainez
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuraio
     */
    public RegistroUsuario() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnpRUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodAdmin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtIdVendedor = new javax.swing.JTextField();
        lblCadmin = new javax.swing.JLabel();
        lblIdVendedor = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gordo´s Restaurant");
        setResizable(false);

        pnpRUsuario.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Registro usuario");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Codigo admin");

        txtCodAdmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("IDEVendedor");

        btnCrear.setBackground(new java.awt.Color(102, 102, 255));
        btnCrear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorder(null);
        btnCrear.setBorderPainted(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 102, 102));
        lblNombre.setText("*");

        txtIdVendedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblCadmin.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblCadmin.setForeground(new java.awt.Color(0, 102, 102));
        lblCadmin.setText("*");

        lblIdVendedor.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblIdVendedor.setForeground(new java.awt.Color(0, 102, 102));
        lblIdVendedor.setText("*");

        javax.swing.GroupLayout pnpRUsuarioLayout = new javax.swing.GroupLayout(pnpRUsuario);
        pnpRUsuario.setLayout(pnpRUsuarioLayout);
        pnpRUsuarioLayout.setHorizontalGroup(
            pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel2))
                    .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(txtIdVendedor))
                            .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(txtNombre)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpRUsuarioLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblCadmin)
                    .addComponent(lblIdVendedor))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnpRUsuarioLayout.setVerticalGroup(
            pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(20, 20, 20)
                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(pnpRUsuarioLayout.createSequentialGroup()
                        .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdVendedor))
                        .addGap(27, 27, 27)
                        .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadmin))))
                .addGap(108, 108, 108)
                .addGroup(pnpRUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnpRUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnpRUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Codigo para el boton regresar
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FormSign cuenta = new FormSign ();
        cuenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
    
    //Codigo para el boton crear un nuevo usuario
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Color verdeTurqueza= new Color(0,102,102);
     
        // Se evalua primero si los cuadros de texto estan vacios
        if(txtNombre.getText().isEmpty()!=true && txtIdVendedor.getText().isEmpty()!=true && txtCodAdmin.getText().isEmpty()!=true)
        {
            // Se evalua si la entrada contiene solo numeros
           if (isNumeric(txtNombre.getText())==false && isNumeric(txtIdVendedor.getText())==false && isNumeric(txtCodAdmin.getText())==true )
           {
               
           
           }
           else
           {
               // Este codigo muestra una indicasion grafica  al usuario para que resuelva los problemas al ingresar datos.
               if(isNumeric(txtNombre.getText())==true)
               {
                   lblNombre.setForeground(Color.red);

               }
               else
               {lblNombre.setForeground(verdeTurqueza);}
               
               if(isNumeric(txtIdVendedor.getText())==true)
               {
                   lblIdVendedor.setForeground(Color.red);

               }
               else
               {lblIdVendedor.setForeground(verdeTurqueza);}
               
               
               if(isNumeric(txtCodAdmin.getText())==false)
               {
                   lblCadmin.setForeground(Color.red);
               }
               else
               {lblCadmin.setForeground(verdeTurqueza);}
               JOptionPane.showMessageDialog(null, "- EL nombre no debe de contener numeros \n - El id vendedor debe tener numeros y letras\n  -El codigo admin solo debe d econtener numeros ");
           }


        }
        else
        {
               if(txtNombre.getText().isEmpty()==true)
               {
                   lblNombre.setForeground(Color.red);
                   
               }
               else
               {lblNombre.setForeground(verdeTurqueza);}
               
               if(txtIdVendedor.getText().isEmpty()==true)
               {
                   lblIdVendedor.setForeground(Color.red);
                   
               }
               else
               {lblIdVendedor.setForeground(verdeTurqueza);}
               
               if(txtCodAdmin.getText().isEmpty()==true)
               {
                   lblCadmin.setForeground(Color.red);

               }
               else
               {lblCadmin.setForeground(verdeTurqueza);}
          JOptionPane.showMessageDialog(null, "Se deben de completar todos los campos");
        }
        
        pnpRUsuario.getUI();

        
    }//GEN-LAST:event_btnCrearActionPerformed
 
        // Este metodo se utiliza para evaluar si una entrada es numerica 
    public boolean isNumeric(String Cadena)
    {
        try {
            Integer.parseInt(Cadena);
            return true;
        
        }catch(NumberFormatException err)
        {
            return false;
        }
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCadmin;
    private javax.swing.JLabel lblIdVendedor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnpRUsuario;
    private javax.swing.JTextField txtCodAdmin;
    private javax.swing.JTextField txtIdVendedor;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
