
package Formularios;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;



/**
 *
 * @author Pedro Ernesto Alfaro Lainez
 */
public class FormPrin extends javax.swing.JFrame {
 

       
    public FormPrin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnPedidos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnOrden = new javax.swing.JPanel();
        btnSallir = new javax.swing.JButton();
        btnSallir1 = new javax.swing.JButton();
        btnSallir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gordo´s Restaurant");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(153, 153, 255));
        pnTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        pnTitulo.setName(""); // NOI18N
        pnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel7.setText("Menu del dia ");
        jLabel7.setAlignmentY(0.0F);
        pnTitulo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 84));

        getContentPane().add(pnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1320, 84));

        pnPedidos.setBackground(new java.awt.Color(0, 102, 102));
        pnPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\reybi\\Downloads\\Proyecto_Desarrollo\\PRN215_GRUPO_1_2\\PRN215_GRUPO_1_2\\build\\classes\\imagenes proyecto\\nachos.jpg")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\reybi\\Downloads\\Proyecto_Desarrollo\\PRN215_GRUPO_1_2\\PRN215_GRUPO_1_2\\build\\classes\\imagenes proyecto\\pizza.jpg")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\reybi\\Downloads\\Proyecto_Desarrollo\\PRN215_GRUPO_1_2\\PRN215_GRUPO_1_2\\build\\classes\\imagenes proyecto\\chili.jpg")); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\reybi\\Downloads\\Proyecto_Desarrollo\\PRN215_GRUPO_1_2\\PRN215_GRUPO_1_2\\build\\classes\\imagenes proyecto\\amburguesa.png")); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\reybi\\Downloads\\Proyecto_Desarrollo\\PRN215_GRUPO_1_2\\PRN215_GRUPO_1_2\\build\\classes\\imagenes proyecto\\tacos.png")); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\reybi\\Downloads\\Proyecto_Desarrollo\\PRN215_GRUPO_1_2\\PRN215_GRUPO_1_2\\build\\classes\\imagenes proyecto\\hotdog.jpg")); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("$ 4.50");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("$ 6.50");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("$ 3.50");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("$ 6.50");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("$ 7.00");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("$ 7.00");

        javax.swing.GroupLayout pnPedidosLayout = new javax.swing.GroupLayout(pnPedidos);
        pnPedidos.setLayout(pnPedidosLayout);
        pnPedidosLayout.setHorizontalGroup(
            pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidosLayout.createSequentialGroup()
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel3)
                        .addGap(203, 203, 203)
                        .addComponent(jLabel4))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel6)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel5)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnPedidosLayout.setVerticalGroup(
            pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(pnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 76, -1, 840));

        pnOrden.setBackground(new java.awt.Color(255, 255, 255));
        pnOrden.setForeground(new java.awt.Color(204, 204, 204));
        pnOrden.setAlignmentX(0.0F);
        pnOrden.setAlignmentY(0.0F);
        pnOrden.setLayout(new javax.swing.BoxLayout(pnOrden, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(pnOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 84, 744, 828));

        btnSallir.setBackground(new java.awt.Color(51, 102, 255));
        btnSallir.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        btnSallir.setText("Administrador");
        btnSallir.setAlignmentY(0.0F);
        getContentPane().add(btnSallir, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 912, 396, 72));

        btnSallir1.setBackground(new java.awt.Color(204, 0, 0));
        btnSallir1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        btnSallir1.setText("Exit");
        btnSallir1.setAlignmentY(0.0F);
        btnSallir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSallir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSallir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 912, 588, 72));

        btnSallir2.setBackground(new java.awt.Color(0, 204, 204));
        btnSallir2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        btnSallir2.setText("Ir a la orden");
        btnSallir2.setAlignmentY(0.0F);
        getContentPane().add(btnSallir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 912, 348, 72));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Codigo para el boton amburguesa
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // Camps de clase
        int x=0;
        int y=0;
      
        // Crea un cuadro de texto en el panel pnOrden
        
        // Crea un boton en el panel pnMas
        Font tamañoLetra = new Font("calibri ligth", Font.BOLD,14);
        JTextField mas = new JTextField();
        mas.setBounds(x,y,744,100);
        mas.setFont(tamañoLetra);
        mas.setText("Amburguesa de 1/4 de libra $6.50 ");
        mas.setEnabled(true);
        mas.setForeground(Color.black);
        mas.setVisible(true);
        pnOrden.add(mas);
        pnOrden.updateUI();
        x+=100;
        y+=100;
        pnOrden.add(mas);
        pnOrden.updateUI();
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    // Este codigo es para salir de la aplicasion 
    private void btnSallir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSallir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSallir1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSallir;
    private javax.swing.JButton btnSallir1;
    private javax.swing.JButton btnSallir2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnOrden;
    private javax.swing.JPanel pnPedidos;
    private javax.swing.JPanel pnTitulo;
    // End of variables declaration//GEN-END:variables
}
